solana airdrop 2 9MJzW1oEzvjHnmdLdoGRGr1i4hu82g7eEEnxvmifcDZD --url https://api.devnet.solana.com
solana airdrop 2 9MJzW1oEzvjHnmdLdoGRGr1i4hu82g7eEEnxvmifcDZD --url https://api.devnet.solana.com
solana airdrop 2 9MJzW1oEzvjHnmdLdoGRGr1i4hu82g7eEEnxvmifcDZD --url https://api.devnet.solana.com
solana airdrop 2 9MJzW1oEzvjHnmdLdoGRGr1i4hu82g7eEEnxvmifcDZD --url https://api.devnet.solana.com
solana airdrop 2 9MJzW1oEzvjHnmdLdoGRGr1i4hu82g7eEEnxvmifcDZD --url https://api.devnet.solana.com
solana airdrop 2 9MJzW1oEzvjHnmdLdoGRGr1i4hu82g7eEEnxvmifcDZD --url https://api.devnet.solana.com
solana airdrop 2 9MJzW1oEzvjHnmdLdoGRGr1i4hu82g7eEEnxvmifcDZD --url https://api.devnet.solana.com
solana airdrop 2 9MJzW1oEzvjHnmdLdoGRGr1i4hu82g7eEEnxvmifcDZD --url https://api.devnet.solana.com
solana airdrop 2 9MJzW1oEzvjHnmdLdoGRGr1i4hu82g7eEEnxvmifcDZD --url https://api.devnet.solana.com
solana airdrop 2 9MJzW1oEzvjHnmdLdoGRGr1i4hu82g7eEEnxvmifcDZD --url https://api.devnet.solana.com
solana airdrop 2 9MJzW1oEzvjHnmdLdoGRGr1i4hu82g7eEEnxvmifcDZD --url https://api.devnet.solana.com
