solana airdrop 2 qyyyaWSn5SckRW4h8nTXjFxxY2XR6MVrVve4mefexZq --url https://api.devnet.solana.com
solana airdrop 2 qyyyaWSn5SckRW4h8nTXjFxxY2XR6MVrVve4mefexZq --url https://api.devnet.solana.com
solana airdrop 2 qyyyaWSn5SckRW4h8nTXjFxxY2XR6MVrVve4mefexZq --url https://api.devnet.solana.com
solana airdrop 2 qyyyaWSn5SckRW4h8nTXjFxxY2XR6MVrVve4mefexZq --url https://api.devnet.solana.com
solana airdrop 2 qyyyaWSn5SckRW4h8nTXjFxxY2XR6MVrVve4mefexZq --url https://api.devnet.solana.com
solana airdrop 2 qyyyaWSn5SckRW4h8nTXjFxxY2XR6MVrVve4mefexZq --url https://api.devnet.solana.com
solana airdrop 2 qyyyaWSn5SckRW4h8nTXjFxxY2XR6MVrVve4mefexZq --url https://api.devnet.solana.com
solana airdrop 2 qyyyaWSn5SckRW4h8nTXjFxxY2XR6MVrVve4mefexZq --url https://api.devnet.solana.com
solana airdrop 2 qyyyaWSn5SckRW4h8nTXjFxxY2XR6MVrVve4mefexZq --url https://api.devnet.solana.com
solana airdrop 2 qyyyaWSn5SckRW4h8nTXjFxxY2XR6MVrVve4mefexZq --url https://api.devnet.solana.com
